### ISSUE TITLE
[BUG] `fzf`'s preview overlaps with its candidates

### ISSUE THREAD

**Issue by NightMachinery** [ms-jpq/sad#71]
![image](https://user-images.githubusercontent.com/36224762/119963492-69390200-bfbd-11eb-9f88-20887b6e01e5.png)

This might be an upstream bug though.

**Comment by ms-jpq** [comment]
Are you using a non English locale? 

there is a fzf bug where the width calculation is wrong if your locale isnt English, so I just added a small thing that sets the `fzf` locale to `C`.

It's in the [newest `v0.4.13` release](https://github.com/ms-jpq/sad/releases/tag/ci_0.4.13_2021-08-14_16-25).

Other than that it's probably an upstream issue. how `sad` works is that it has actually no UI of it self, it just generates pure text output for `fzf` and `delta`. So if either their UIs are borked, then its probably not because im generating some super special thing.

**Comment by NightMachinery** [comment]
No, I don’t use a non-English locale.

Closing the issue as it is indeed most probably an upstream one.
